import { CatalogCourse, course } from "./types";

/** College Board AP courses (current catalog). */
export const AP_COURSES: CatalogCourse[] = [
  course("AP", "CAP-SEM", "AP Seminar", "AP Capstone"),
  course("AP", "CAP-RES", "AP Research", "AP Capstone"),
  course("AP", "ART-HIST", "AP Art History", "Arts"),
  course("AP", "MUSIC-TH", "AP Music Theory", "Arts"),
  course("AP", "ART-2D", "AP 2-D Art and Design", "Arts"),
  course("AP", "ART-3D", "AP 3-D Art and Design", "Arts"),
  course("AP", "ART-DRAW", "AP Drawing", "Arts"),
  course("AP", "ENG-LANG", "AP English Language and Composition", "English"),
  course("AP", "ENG-LIT", "AP English Literature and Composition", "English"),
  course("AP", "HIST-EU", "AP European History", "History & Social Sciences"),
  course("AP", "HIST-US", "AP United States History", "History & Social Sciences"),
  course("AP", "HIST-WH", "AP World History: Modern", "History & Social Sciences"),
  course("AP", "HUM-GEO", "AP Human Geography", "History & Social Sciences"),
  course("AP", "GOV-US", "AP United States Government and Politics", "History & Social Sciences"),
  course("AP", "GOV-COMP", "AP Comparative Government and Politics", "History & Social Sciences"),
  course("AP", "PSY", "AP Psychology", "History & Social Sciences"),
  course("AP", "AFRAM", "AP African American Studies", "History & Social Sciences"),
  course("AP", "MACRO", "AP Macroeconomics", "History & Social Sciences"),
  course("AP", "MICRO", "AP Microeconomics", "History & Social Sciences"),
  course("AP", "MATH-PRE", "AP Precalculus", "Math & Computer Science"),
  course("AP", "CALC-AB", "AP Calculus AB", "Math & Computer Science"),
  course("AP", "CALC-BC", "AP Calculus BC", "Math & Computer Science"),
  course("AP", "STATS", "AP Statistics", "Math & Computer Science"),
  course("AP", "CSA", "AP Computer Science A", "Math & Computer Science"),
  course("AP", "CSP", "AP Computer Science Principles", "Math & Computer Science"),
  course("AP", "BIO", "AP Biology", "Sciences"),
  course("AP", "CHEM", "AP Chemistry", "Sciences"),
  course("AP", "ENVSCI", "AP Environmental Science", "Sciences"),
  course("AP", "PHY1", "AP Physics 1: Algebra-Based", "Sciences"),
  course("AP", "PHY2", "AP Physics 2: Algebra-Based", "Sciences"),
  course("AP", "PHYC-M", "AP Physics C: Mechanics", "Sciences"),
  course("AP", "PHYC-EM", "AP Physics C: Electricity and Magnetism", "Sciences"),
  course("AP", "LANG-CHI", "AP Chinese Language and Culture", "World Languages"),
  course("AP", "LANG-FRE", "AP French Language and Culture", "World Languages"),
  course("AP", "LANG-GER", "AP German Language and Culture", "World Languages"),
  course("AP", "LANG-ITA", "AP Italian Language and Culture", "World Languages"),
  course("AP", "LANG-JPN", "AP Japanese Language and Culture", "World Languages"),
  course("AP", "LANG-LAT", "AP Latin", "World Languages"),
  course("AP", "LANG-SPA", "AP Spanish Language and Culture", "World Languages"),
  course("AP", "LIT-SPA", "AP Spanish Literature and Culture", "World Languages"),
];
